import { useState, useEffect, useContext } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './index.module.css'
import { AppContext } from '../context/App'

const fetchUsers = async (accessToken: string) => {
  const res = await fetch(
    'http://localhost:4000/api/v1/users',
    {
      method: 'GET',
      headers: {
        'Content-type': 'application/json',
        'Authorization': `Bearer ${accessToken}`,
      },
    }
  )

  if (res.status === 200) {
    const result = await res.json()
    return { data: result, error: null }
  }

  return { data: null, error: Error('res.status is not 200. fetch Users') }
}

const Index: NextPage = () => {
  const [data, setData] = useState<any>(null)
  const [error, setError] = useState<any>(null)
  const context = useContext(AppContext)

  useEffect(() => {
    const fetchUsersInUseEffect = async (accessToken: string) => {
      const { data, error } = await fetchUsers(accessToken)
      setData(data)
      setError(error)
    }

    if (!data) {
      fetchUsersInUseEffect(context.accessToken ? context.accessToken : "")
    }
  }, [data, error, context.accessToken])

  if (error) {
    return (
      <div>Error!</div>
    )
  }

  if (!data) {
    return (
      <div>Loading...</div>
    )
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data.data.map((user: any, i: number) => (
          <div key={i}>
            <span>{user.id}</span>
            <span>{user.email}</span>
            <span>{user.name}</span>
          </div>
        ))}
      </main>
    </>
  )
}

export default Index
